// frontend/pages/report-preview.tsx

import { useEffect, useState } from "react";
import Image from "next/image";

export default function ReportPreview() {
  const [data, setData] = useState<any | null>(null);

  useEffect(() => {
    const raw = sessionStorage.getItem("latestProject");
    if (raw) setData(JSON.parse(raw));
  }, []);

  const downloadPDF = async () => {
    const res = await fetch("/api/pdf-report", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(data),
    });
    if (res.ok) {
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `Site_Report_${data.projectName || "project"}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  const emailPDF = async () => {
    const res = await fetch("/api/email-report", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(data),
    });
    if (res.ok) alert("Report sent to client.");
    else alert("Failed to send email.");
  };

  if (!data) return <div className="p-10 text-gray-600">Loading preview...</div>;

  return (
    <div className="max-w-3xl mx-auto bg-white border border-gray-300 rounded shadow-md p-8 space-y-6 print:bg-white print:shadow-none">
      {/* Header */}
      <div className="flex items-center justify-between">
        <Image src="/assets/gbta-logo.jpg" alt="GBTA Logo" width={120} height={80} />
        <h1 className="text-2xl font-bold text-gray-800 text-right">Pre-Contract Site Assessment Report</h1>
      </div>

      {/* Client Details */}
      <section className="text-sm text-gray-800">
        <h2 className="font-semibold text-lg border-b pb-1 mb-2">Client Information</h2>
        <p><strong>Client Name:</strong> {data.firstName} {data.lastName}</p>
        <p><strong>Project Name:</strong> {data.projectName}</p>
        <p><strong>Services Requested:</strong> {data.services?.join(", ")}</p>
      </section>

      {/* Site Address */}
      <section className="text-sm text-gray-800">
        <h2 className="font-semibold text-lg border-b pb-1 mb-2">Site Details</h2>
        <p><strong>Address:</strong> {data.street}, {data.suburb} {data.state} {data.postcode}</p>
        <p><strong>Council:</strong> {data.council || "—"}</p>
      </section>

      {/* Geo & Risk Data */}
      <section className="text-sm text-gray-800 grid grid-cols-2 gap-4">
        <div><strong>Elevation:</strong> {data.elevation || "—"} m</div>
        <div><strong>Distance to Coast:</strong> {data.distanceToCoast || "—"} km</div>
        <div><strong>Wind Zone:</strong> {data.windZone || "—"}</div>
        <div><strong>BAL Rating:</strong> {data.balRating || "—"}</div>
        <div><strong>Benchmark 1:</strong> {data.benchmark1 || "—"}</div>
        <div><strong>Benchmark 2:</strong> {data.benchmark2 || "—"}</div>
        <div><strong>Footing Recommendation:</strong> {data.footingRecommendation || "—"}</div>
        <div><strong>Risk Summary:</strong> {data.riskSummary || "—"}</div>
      </section>

      {/* Action Buttons */}
      <div className="flex gap-4 justify-end pt-6">
        <button
          onClick={downloadPDF}
          className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700"
        >
          Download PDF
        </button>
        <button
          onClick={emailPDF}
          className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700"
        >
          Email to Client
        </button>
      </div>

      <div className="pt-4 border-t text-sm text-gray-500 text-center">
        Report generated by Corporate AI Solutions — www.corporateaisolutions.com
      </div>
    </div>
  );
}
